### PR TITLE
New cpp11::messages with opt-in fmt formatting

### LINKED ISSUE #208: Add `cpp11::message()`
Add another option instead of `cpp11:stop()` and `cpp11::warnings()` for non errors and warnings.

Add to protect.hpp

### PR DESCRIPTION
**Pull request by sbearrows**
Fixes #208

Let me know what you think!

### CODE REVIEW

**Comment by sbearrows** [comment]
I had a bunch of merge conflicts so I'm not surprised that `format_check` is failing. I'm gonna wait to see if the other checks pass and then I'l fix it!

**Comment by jimhester** [comment]
could you rebase this branch on the current master? I can help you do it in our meeting if you need to, but assuming r-lib/master is the 'upstream' remote you would do something like.

```
git checkout feature-message_fmt
git fetch upstream
git rebase upstream/master
```

I think your branch is based on your forks master branch, which is very out of date at this point, so we are getting a bunch of extra commits in the PR.

**Comment by sbearrows** [comment]
Yes, please and thank you!

**Comment by jimhester** [comment]
Thanks a ton!

**Pull request merged**
