### PR TITLE
Vendoring

### PR DESCRIPTION
**Pull request by pachadotdev**
#340 but without the breaking changes

### CODE REVIEW

**Comment by pachadotdev** [comment]
@krlmlr hi, this allows u to vendor to src/vendor!
@hadley i keep the unlink() function in vendor.R examples to pass the local check(), but that then creates problems with pkgdown

**Comment by krlmlr** [comment]
Thanks. I'd wait for a comment on if we want to vendor into `src/vendor` at all. Perhaps there's a reason for vendoring into `inst/include` ?

**Comment by pachadotdev** [comment]
> Thanks. I'd wait for a comment on if we want to vendor into `src/vendor` at all. Perhaps there's a reason for vendoring into `inst/include` ?

what i saw with check(), is that it doesn't like to put files in src, but if i vendor in src/vendor in a pkg project, it passes all checks for that another pkg

**Comment by krlmlr** [comment]
- The checks in this PR are failing
- This PR seems to have a bit of noise
- We don't know the maintainers' perspective on if this PR is a good, so I'm not sure if it's worth addressing the first two issues at all

Let's not spend too much time here for now?

**Comment by pachadotdev** [comment]
> * The checks in this PR are failing
> 
>     * This PR seems to have a bit of noise
> 
>     * We don't know the maintainers' perspective on if this PR is a good, so I'm not sure if it's worth addressing the first two issues at all
> 
> 
> Let's not spend too much time here for now?

sure, i was following from the vendoring in https://github.com/r-dbi/RPostgres/tree/main/src/vendor/boost

**Pull request closed without merging**
