### PR TITLE
Add install instructions for clang version 10 to cpp11 webpage

### LINKED ISSUE #190: Add homebrew tap clang-format@10 instructions to cpp11 webpage
Because cpp11 uses clang version 10 for clang-format, having instructions for how to install v 10 to the webpage could be useful. Thankfully @jimhester made a homebrew tap for this.

### PR DESCRIPTION
**Pull request by sbearrows**
Let me know if I should add more specific install instructions about the new homebrew tap!

fixes #190

### CODE REVIEW

**Comment by jimhester** [comment]
Yeah make it very specific, exactly what commands you need to run.

**Comment by sbearrows** [comment]
Is this NEWS worthy?

**Comment by jimhester** [comment]
We generally don't update news for documentation only changes.

**Comment by jimhester** [comment]
Thanks, this looks great!

**Pull request merged**
