### PR TITLE
as_cpp<int>(LGLSXP scalar)

### PR DESCRIPTION
**Pull request by romainfrancois**
This is mostly useful for `NA` : 

``` r
cpp11::cpp_function("int echo(int x){ return x; }")
str(echo(1))
#>  int 1
str(echo(2L))
#>  int 2
str(echo(NA))
#>  int NA
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

### CODE REVIEW

**Comment by jimhester** [comment]
Hmm, I am not sure we want this though, I think you should have to pass `NA_integer_` in this case. I generally have tried to avoid implicit coercions in the interfaces.

**Comment by romainfrancois** [comment]
I'd say most users regard `NA` as typeless, and I figured since there already is a branch for `REALSXP` it would not be too bad. Maybe that could be limited to `NA` and still abort for TRUE and FALSE.

**Comment by jimhester** [comment]
Sure, doing the conversion for NA only makes sense to me, and I guess it the coercion is relatively benign for this case.

**Comment by romainfrancois** [comment]
🤔 now that I've seen that `as_cpp<T>` can handle various types of integer for `T` and that NA_real also isn't handled, maybe it's not needed at all/confusing. 

``` r
cpp11::cpp_function('int echo(int x){
  return x;
}')
echo(NA_real_)
#> Error: Expected single integer value
```

<sup>Created on 2020-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by romainfrancois** [comment]
I mean we would have to come up with NA for `long long` etc ... maybe instead for scalars that might be NA, we could have some wrapper class that would deal with it, i.e. something like: 

```
template <typename T>
scalar {
  scalar(SEXP from) : from_(from){ // assert that this is indeed a scalar of a type compatible to T}

  bool is_na();
  inline T get();

  SEXP from;
};
```

**Pull request merged**
